# Generated by Django 5.2.7 on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('DOCTOR', 'Médico'), 
                    ('NURSE', 'Enfermero/a'), 
                    ('ADMIN', 'Administrativo'), 
                    ('RECEPTIONIST', 'Recepcionista'), 
                    ('PATIENT', 'Paciente')
                ], 
                default='DOCTOR', 
                max_length=20
            ),
        ),
    ]
