# Generated by Django 5.2.7 on 2025-11-25 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('patient_name', models.CharField(max_length=160)),
                ('patient_id_number', models.CharField(help_text='Número de identificación del paciente', max_length=50)),
                ('patient_birth_date', models.DateField()),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('patient_address', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnóstico principal')),
                ('symptoms', models.TextField(blank=True, help_text='Síntomas reportados')),
                ('observations', models.TextField(blank=True, help_text='Observaciones del médico')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('ARCHIVED', 'Archivada')], default='DRAFT', max_length=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notas específicas sobre el procedimiento realizado')),
                ('procedure_date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='medical_records.medicalrecord')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical_services.medicalprocedure')),
            ],
        ),
    ]
