# Generated by Django 5.2.7 on 2025-11-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('CLINIC', 'Clínica'), ('HOSPITAL', 'Hospital'), ('LABORATORY', 'Laboratorio'), ('EMERGENCY', 'Urgencias')], default='CLINIC', max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Capacidad de pacientes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medical Facilities',
                'ordering': ['-created_at'],
            },
        ),
    ]
